### PR TITLE
Add last transaction endpoint

### PR DESCRIPTION
**Pull request by mlabarca**
I added this endpoint since it's missing. Sorry if I messed up in anything and feel free to refactor. :see_no_evil:

### CODE REVIEW

**Comment by philipqnguyen** [comment]
@mlabarca Thanks for doing this! This PR is pretty much identical to a PR submitted by @RonWalker22 in #8. He closed the PR, but I'm not sure if he is working on another PR for that or not. However, pretty much my comment on #8 applies to this PR too.

For convenience sake, I've copied and pasted the comment from #8. Let me know what you think of it, and if you'd be able to work on it. You could possibly co-author commits with @RonWalker22 if he has anything that's work in progress.

----

So the `api/txs/last` returns an array of transactions ids (and a couple other fields):
```json
{
   "Right":[
      {
         "cteId":"d5efca4b13c5001c8cbc5617523a7562d6746ff6e454887ba28205e22c854d32",
         "cteTimeIssued":1516154031,
         "cteAmount":{
            "getCoin":"548416093154"
         }
      },
      {
         "cteId":"a3d4531f8955e69b922bee29b1cb615ebcb7d48aba0d1fd132553b9820c30869",
         "cteTimeIssued":1516153991,
         "cteAmount":{
            "getCoin":"548441342333"
         }
      },
      ...
   ]
}
```

Inside the "Right" key in that JSON is an array of transaction objects. So I think it would be more representative if we make it so that `Transaction.latest` returns an Array of instantiated transaction objects.

For example this would allow the users to be able to do things like this:
```ruby
transactions = Transaction.latest #=>
# [#<CardanoExplorer::Transaction ...>, #<CardanoExplorer::Transaction ...>, #<CardanoExplorer::Transaction ...>]

# Then, the user can do things like:
transactions.each { |transaction| .... }
transactions.last.summary #=> { ... }
transactions.first.summary #=> { ... }
transactions[3].summary #=> { ... }
```

I know right now the Base class doesn't support that, and it was my fault for defining a Base class so early on in the development of this gem. However, we can make changes to the Base class to support this.

First what we can do is make the HTTP request related methods to become a class method like so:
```
  class Base

   # Other code

  private

    def self.get(path, options = {})
      HTTParty.get "#{root_url}/#{endpoint}/#{path}", query: options
    end

    def self.root_url
      CardanoExplorer.configuration.root_url
    end

    def self.endpoint
      raise NotImplementedError, '#endpoint not defined in child class'
    end

    def get(path, options = {})
      self.class.get path, options
    end
  end
```

In Transaction class we can add this to return an Array of instantiated Transaction objects:
``` ruby
# transaction.rb
    def self.latest
      get('last').parsed_response['Right'].map {|txs| new txs['cteId']}
    end
```

We also need to make sure that the `endpoint` method in all the other classes become a class method as well.
```
  private

    def self.endpoint
      # whatever their respective endpoints are.
    end
```

Sorry for such a big comment. What do you or anyone else think of that approach?

**Comment by mlabarca** [comment]
I wish I had read that on an issue before hand 😔 for now let's close this
pr and maybe open a feature issue with this plan/refactor. I was sort of
thinking the same on how the latest method should work but couldn't do it
without that changing the others into class methods as well.

I could probably work a bit on this on the next weekend if nothing else
comes up, unless some else beats me to it!

On Jan 21, 2018 5:19 PM, "Philip Q Nguyen" <notifications@github.com> wrote:

@mlabarca <https://github.com/mlabarca> Thanks for doing this! This PR is
pretty much identical to a PR submitted by @RonWalker22
<https://github.com/ronwalker22> in #8
<https://github.com/philipqnguyen/cardano_explorer/pull/8>. He closed the
PR, but I'm not sure if he is working on another PR for that or not.
However, pretty much my comment on #8
<https://github.com/philipqnguyen/cardano_explorer/pull/8> applies to this
PR too.

For convenience sake, I've copied and pasted the comment from #8
<https://github.com/philipqnguyen/cardano_explorer/pull/8>. Let me know
what you think of it, and if you'd be able to work on it. You could
possibly co-author commits with @RonWalker22
<https://github.com/ronwalker22> if he has anything that's work in progress.
------------------------------

So the api/txs/last returns an array of transactions ids (and a couple
other fields):

{
   "Right":[
      {
         "cteId":"d5efca4b13c5001c8cbc5617523a7562d6746ff6e454887ba28205e22c854d32",
         "cteTimeIssued":1516154031,
         "cteAmount":{
            "getCoin":"548416093154"
         }
      },
      {
         "cteId":"a3d4531f8955e69b922bee29b1cb615ebcb7d48aba0d1fd132553b9820c30869",
         "cteTimeIssued":1516153991,
         "cteAmount":{
            "getCoin":"548441342333"
         }
      },
      ...
   ]
}

Inside the "Right" key in that JSON is an array of transaction objects. So
I think it would be more representative if we make it so that
Transaction.latest returns an Array of instantiated transaction objects.

For example this would allow the users to be able to do things like this:

transactions = Transaction.latest #=># [#<CardanoExplorer::Transaction
...>, #<CardanoExplorer::Transaction ...>,
#<CardanoExplorer::Transaction ...>]
# Then, the user can do things like:
transactions.each { |transaction| .... }
transactions.last.summary #=> { ... }
transactions.first.summary #=> { ... }
transactions[3].summary #=> { ... }

I know right now the Base class doesn't support that, and it was my fault
for defining a Base class so early on in the development of this gem.
However, we can make changes to the Base class to support this.

First what we can do is make the HTTP request related methods to become a
class method like so:

  class Base

   # Other code

  private

    def self.get(path, options = {})
      HTTParty.get "#{root_url}/#{endpoint}/#{path}", query: options
    end

    def self.root_url
      CardanoExplorer.configuration.root_url
    end

    def self.endpoint
      raise NotImplementedError, '#endpoint not defined in child class'
    end

    def get(path, options = {})
      self.class.get path, options
    end
  end

In Transaction class we can add this to return an Array of instantiated
Transaction objects:

# transaction.rb
    def self.latest
      get('last').parsed_response['Right'].map {|txs| new txs['cteId']}
    end

We also need to make sure that the endpoint method in all the other classes
become a class method as well.

  private

    def self.endpoint
      # whatever their respective endpoints are.
    end

Sorry for such a big comment. What do you or anyone else think of that
approach?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/philipqnguyen/cardano_explorer/pull/9#issuecomment-359277372>,
or mute the thread

**Comment by philipqnguyen** [comment]
I just created the issue #10 for this. You can close this PR or leave it open and work more on it later, up to you.

Sorry for the mixup @mlabarca

**Comment by mlabarca** [comment]
@philipqnguyen the refactor is done on this pr. Do review it and if it seems fine I'll guess i'll whip up some documentation changes that are missing. Also let me know if you'd prefer to squash all these commits into one.

**Comment by philipqnguyen** [comment]
looks great!!! Ya, can you add the docs? Also squashing the commits would be good =)

**Comment by mlabarca** [comment]
Done!

**Comment by philipqnguyen** [comment]
released in 0.1.3

**Pull request merged**
